### ISSUE TITLE
Support for alternative keyboard layouts

### ISSUE THREAD

**Issue by Twibit** [Kilian/fromscratch#9] opened 2016-02-15 10:37 UTC
It would be nice to be able to undo / redo modifications.

I tried to use cmd+z to undo my last modification but it closed the app.
I'm using an azerty keyboard so there might be an issue there (cmd+w == cmd+z).

**Comment by Kilian** [comment] 2016-02-15 12:05
There is undo and redo support, they're mapped to ctrl/cmd+z and shift+ctrl/cmd+z, independent of your keyboard. Could it be your keyboard is azerty but your keyboard settings are qwerty?

**Comment by Twibit** [comment] 2016-02-15 12:54
Oh right, i didn't saw it in the Edit menu.
This is probably a shortcut problem then.

I'm using it on Mac OS X 10.10.5 and my keyboard is azerty and the settings are set to azerty (french).

Shortcut results (Edit menu) : 
**cmd+Z -> close**
**shift+cmd+Z -> nothing**
cmd+X -> cut
cmd+C -> copy
cmd+V -> paste
**cmd+A -> close**

Other : 
cmd+Q -> close
cmd+R -> refresh ?
**cmd+U -> undo**
**shift+cmd+U -> redo**
cmd+D -> delete line

**Comment by Kilian** [comment] 2016-02-15 13:03
Could be related to #5. keyboard shortcuts, especially on OSX, turned out to be a PITA.

If you switch your keyboard layout to qwerty, does it behave as expected?

**Comment by Twibit** [comment] 2016-02-15 13:08
If i switch to qwerty, undo / redo works with cmd+Z (cmd+W on my keyboard) and cmd+W (cmd+Z on my keyboard) close the app.

**Comment by Twibit** [comment] 2016-02-15 13:09
There are some other problems with the undo/redo.

Shortcut action and menu item action seems incompatible : 
- Write "something"
- cmd+U  (undo)
- Edit / Redo
=> Nothing is displayed

There is a problem with undo/redo in the edit menu : 
 - write "something"
 - Edit / Undo
 - Move the cursor
 - Edit / Redo
=> "something" is written at the new cursor's location

**Comment by Kilian** [comment] 2016-02-15 14:11
I've renamed the issue, it seems that the shortcuts are not correctly transposed for alternative keyboard layouts. To be honest I probably won't look into this any further than seeing if Electron has a solution for this, as I feel this should be handled on that level, and not in FromScratch.

**Comment by fxpasquier** [comment] 2016-03-16 11:59
If you have any ways of getting an ""Azerty-cmd qwerty"" keyboard layout I would be really interested... I would love to be able to switch keyboards while maintaining the shortcuts on the same keys: when you hit a shortcut, your fingers instinctively go somewhere, and I don't want that somewhere to be changed everytime I switch keyboards.

**Comment by Kilian** [comment] 2016-11-10 16:18
With FromScratch 1.2.0 this should be fixed, as it uses a version of Electron that should have fixes for this. Can someone verify this?

**Comment by thomasgrnr** [comment] 2016-12-01 15:38
No it doesnt work for me. I'm on electron 1.4.10 and fromscratch 1.2.0.
Do you need anything to help debuging ?
And nice deduction btw ;)

**Comment by Kilian** [comment] 2016-12-02 13:19
Caused by https://github.com/electron/electron/issues/8116, and applies to keystrokes in combination with ctrl. Should be fixed in Chrome 56. Current build of electron uses chrome 53, so this will be a while away :(

**Closed** 2016-12-08 19:37 UTC
Labels: bug, Electron
