### ISSUE TITLE
Unable to click cursor to the start of any line of text (1.4.1)

### ISSUE THREAD

**Issue by Jamezhall** [Kilian/fromscratch#71] opened 2018-07-31 23:53 UTC
Issue: Cannot click the beginning of a line of text or place cursor there with left mouse click. See below.
Version: 1.4.1
OS: Windows 10

![fs1 4 1-margin-issue](https://user-images.githubusercontent.com/19564725/43493218-31d7247e-9570-11e8-992a-414ee5af8942.gif)

Loving all the new updates - looks like 1.4.1 broke something though. Hope this can help!

**Comment by AndrewWhiteat70ms** [comment] 2018-08-02 15:36
I'm having the same problem, except that when I click that region, I can collapse the text. I think the gutter is too wide, and is overlapping the text.

**Comment by Kilian** [comment] 2018-08-08 07:49
I think #71 and #70 are caused by the same issue, and that is that the gutters (blank area next to the text) are no longer sized correctly. I'll investigate! I think my changes for #44 might've changed this.

**Comment by Jamezhall** [comment] 2018-08-22 00:14
@Kilian Out of interest is there any eta on a fix? Not being able to select the beginning of the line is kind of a bummer 😊
I'm not sure how it works but would a small **fixed** gutter make sense, similar to most IDEs? (as opposed to it scaling?)

**Comment by Juje** [comment] 2018-08-28 06:32
@Kilian For some reason the fold/unfold buttons get clicked if you click in the non click zone.
This can be tested with something like:

```
- Foo
	- Bar
- Foos
- Bas
```

It folds even if you click on `Bas` or `Foos`.
So it looks like the clicking area for the fold/unfold buttons seems to big.

**Comment by Kilian** [comment] 2018-09-01 13:04
I think this is fixed by this version, mac only for now (at least it is for me): https://github.com/Kilian/fromscratch/releases/download/v1.4.2-beta/FromScratch-1.4.2.dmg

**Comment by AndrewWhiteat70ms** [comment] 2018-09-05 15:16
Works for me! Thanks, Killian!

**Comment by Juje** [comment] 2018-09-06 08:01
The issue is indeed fixed :smile: (using the latest version from master (6861e8cffa64f9c6506ac92296996eb5a0040ec7)).

But the clicking area is still too big in my honest opinion.

For the below text when you click next to the word `test` it closes the whole paragraph above it which is weird to be honest.
```
You can type neat arrows like these: ->, -->, ->> and =>, courtesy of the font "Fira Code".

	FromScratch also does automatic indenting
	and more. So delete this text & let's go!+
	
test
```

But you can again click on words at the beginning of the line which is really good :smile:

**Comment by Kilian** [comment] 2018-09-06 08:16
You're right, but that's less easy to change, since it's internal listeners that are being set by codemirror (the text editor powering from scratch) that I don't have direct access to. I'll see if there are ways to improve that!

**Comment by Jamezhall** [comment] 2018-09-17 23:20
Looking forward to the M$ Windows version! (sorry, i'm a windows pleb - not by choice - its what i'm using at work) :(

**Comment by Kilian** [comment] 2018-09-22 19:05
released: https://github.com/Kilian/fromscratch/releases/tag/v1.4.2

**Closed by Kilian** 2018-09-22 19:05 UTC
